//
// Created by Jonathan Moallem on 23/1/21.
//

#ifndef A_DARK_DISCOMFORT_SPLASHSCREENSERIALISER_H
#define A_DARK_DISCOMFORT_SPLASHSCREENSERIALISER_H



class SplashScreenSerialiser {

};



#endif //A_DARK_DISCOMFORT_SPLASHSCREENSERIALISER_H
