name: Formatting

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  formatting:
    runs-on: macos-latest
    steps:
      - name: perform checkout
        uses: actions/checkout@v4

      - name: install latest clang-format
        run: brew install clang-format

      - name: make format-check
        run: make format-check