name: macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

        # Setup dependencies
      - name: setup dependencies
        run: |
          make setup
        # Build the app
      - name: build project
        run: |
          make bin/app
        # Clean the binaries
      - name: clean
        run: make clean

        # Try build app in another compiler
      - name: make bin/app CXX=g++
        run: |
          make bin/app CXX=g++