name: macOS

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: perform checkout
        uses: actions/checkout@v4

      - name: perform setup
        run: ./scripts/setup.sh

      - name: build all targets
        run: make

      - name: run tests
        run: |
          cd ./bin/tests/build
          ./app

      - name: compress output
        shell: bash
        run: tar -cvf ./macos.tar -C ./output .

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos_output
          path: ./macos.tar