name: macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: perform setup
        run: ./scripts/setup.sh

      - name: build and package executable
        run: make package