name: macOS

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    # Run setup

    - name: make setup
      run: make setup

    # Build and clean

    - name: make build
      run: make build

    - name: make clean
      run: make clean

    # Rebuild with g++

    - name: make build CXX=g++
      run: make build CXX=g++
