name: macOS

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    # Build and clean

    - name: update submodules
      run: git submodule update --init --recursive

    - name: make
      run: make

    - name: make clean
      run: make clean

    # Rebuild with g++

    - name: make CXX=g++
      run: make CXX=g++
