name: macOS

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: perform checkout
        uses: actions/checkout@v4

    - name: perform setup
      run: ./scripts/setup.sh

    - name: build all targets
      run: make