name: macos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup dependencies
        run: |
          ./scripts/setup.sh

      - name: build project
        run: |
          make package DEBUG=0

      - name: clean
        run: make clean