name: Tests

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies

      - name: update apt
        run: sudo apt-get update

      - name: install raylib dependencies
        run: sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev

      # Run setup

      - name: make setup
        run: make setup

      # Run tests

      - name: make test
        working-directory: ./vendor/engine
        run: make test