name: Ubuntu

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: update apt
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential libx11-xcb-dev \
          libxkbcommon-dev libwayland-dev libxrandr-dev

      - name: install glfw dependencies
        run: sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: setup dependencies
        run: |
          ./scripts/setup.sh

      - name: make bin/app
        run: |
          make package DEBUG=0
  

      - name: make clean
        run: make clean