name: Windows

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    
    steps:
      - name: perform checkout
        uses: actions/checkout@v4

      - name: perform setup
        run: ./scripts/setup.ps1
        
      - name: build all targets
        run: mingw32-make

      - name: run tests
        run: |
          cd ./bin/tests/build
          ./app.exe
