name: Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: PowerShell

    steps:
      - uses: actions/checkout@v2

      - name: Setup dependencies
        run: |
          ./scripts/setup.bat

      - name: Compile Project
        run: |
          mingw32-make package DEBUG=0

      - name: Clean Project
        run: mingw32-make clean