name: Windows

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: PowerShell
    
    steps:
    - uses: actions/checkout@v2

    - name: perform setup
      run: ./scripts/Setup.ps1
      
    - name: build all targets
      run: mingw32-make