name: Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: PowerShell

    steps:
      - uses: actions/checkout@v2

      - name: perform setup
        run: ./scripts/setup.bat

      - name: build and package executable
        run: mingw32-make package